In [1]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.full(8, 3.3)

array([3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [6]:
np.linspace(0, 2, 13)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ,
       1.66666667, 1.83333333, 2.        ])

Multidimensional arrays

In [7]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.full((2,3,4,5), 3)

array([[[[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]],


       [[[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]]])

In [14]:
np.array(
    [[1, 2, 3],
    [1, 2],
    [1, 2, 3]]
)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [17]:
arr = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [6, 7, 8]]
)

In [27]:
arr[0, 2] == arr[0][2] == 3

True

In [28]:
arr[:]

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [29]:
arr[:, 1]

array([2, 5, 7])

In [31]:
arr[0, :] = arr[0]

In [33]:
arr[:, 0] = np.full(3, 9)
arr

array([[9, 2, 3],
       [9, 5, 6],
       [9, 7, 8]])

In [37]:
np.random.rand(6, 3)

array([[0.79363745, 0.58000418, 0.1622986 ],
       [0.70075235, 0.96455108, 0.50000836],
       [0.88952006, 0.34161365, 0.56714413],
       [0.42754596, 0.43674726, 0.77655918],
       [0.53560417, 0.95374223, 0.54420816],
       [0.08209492, 0.3663424 , 0.8508505 ]])

In [41]:
np.random.seed(2) # to make random result same, to be able to reproduce
np.random.rand(6, 3) # uniform distribution

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987],
       [0.78533515, 0.85397529, 0.49423684]])

In [42]:
np.random.seed(2) # to make random result same, to be able to reproduce
np.random.randn(6, 3) # normal distribution

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222],
       [-0.90900761,  0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545,  0.53905832],
       [-0.5961597 , -0.0191305 ,  1.17500122]])

Elementwise operations

In [6]:
n = np.arange(6)
n

array([0, 1, 2, 3, 4, 5])

In [10]:
b =((n + 1) * 2) ** 2
b

array([  4,  16,  36,  64, 100, 144])

In [12]:
n + b

array([  4,  17,  38,  67, 104, 149])

In [34]:
n * b # not same as dot product!

array([ 400, 3200,   72,  192,  400,  720])

In [13]:
n >= 3

array([False, False, False,  True,  True,  True])

In [15]:
n[1] = 200
b > n

array([ True, False,  True,  True,  True,  True])

In [25]:
n[0] = 100
n[n > b]

array([100, 200])

Aggregation operations

In [27]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a.min()

0

In [29]:
a.max()

9

In [30]:
a.sum()

45

In [33]:
a.mean()

4.5